[www]
user = www-data
group = www-data
listen = /var/run/php/php8.1-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 200
pm.start_servers = 50
pm.min_spare_servers = 25
pm.max_spare_servers = 75
pm.max_requests = 1000

request_terminate_timeout = 60
request_slowlog_timeout = 10
slowlog = /var/log/php8.1-fpm-slow.log

php_admin_value[memory_limit] = 512M
php_admin_value[max_execution_time] = 60
php_admin_value[opcache.enable] = 1
php_admin_value[opcache.memory_consumption] = 1024
php_admin_value[opcache.max_accelerated_files] = 20000
php_admin_value[opcache.validate_timestamps] = 0
php_admin_value[opcache.jit] = 1255
php_admin_value[opcache.jit_buffer_size] = 512M